### ISSUE TITLE
Cleanup CI warnings

### ISSUE THREAD

**Issue by tyeth** [adafruit/Adafruit_Wippersnapper_Arduino#663]
Since adding the caching of nanopb logic, there is a warning if the job doesn't save to the cache.
Resolve with something like:
```
- name: Check if cache exists
  id: cache-check
  uses: actions/cache@v4
  with:
    path: ./nanopb-0.4.8.tar.gz
    key: nanopb-0.4.8
    enableCrossOsArchive: false

- name: Cache nanopb
  if: steps.cache-check.outputs.cache-hit != 'true'
  uses: actions/cache@v4
  with:
    path: ./nanopb-0.4.8.tar.gz
    key: nanopb-0.4.8
    enableCrossOsArchive: false

```
